module.exports = {
  parserOptions: {
    ecmaVersion: 2020,
    sourceType: 'module',
  },
  plugins: [
    'eslint-comments',
    'import',
    'flowtype',
    'promise',
    'unicorn',
    'json-format',
  ],
  extends: [
    'airbnb-base',
    'eslint:recommended',
    'plugin:import/errors',
    'plugin:import/warnings',
    'plugin:promise/recommended',
    'plugin:yml/standard',
    'plugin:json/recommended',
    'plugin:jsonc/recommended-with-jsonc',
    'plugin:json-schema-validator/recommended',
  ],
  env: {
    browser: true,
    commonjs: true,
    es6: true,
    node: true,
  },
  rules: {
    camelcase: 0,
    eqeqeq: [2, 'always', { null: 'ignore' }],
    'max-classes-per-file': 0,
    'prefer-destructuring': 0,
    'class-methods-use-this': 0,
    'implicit-arrow-linebreak': 0,
    'lines-between-class-members': 0,
    'consistent-return': 0,
    'func-names': [1, 'never', { generators: 'as-needed' }],
    'unicorn/filename-case': [1, { case: 'kebabCase' }],
    'no-bitwise': 0,
    'no-continue': 0,
    'no-lonely-if': 0,
    'no-multi-assign': 0,
    'no-nested-ternary': 0,
    'no-inner-declarations': 0,
    'no-unused-expressions': 0,
    'no-return-assign': [2, 'except-parens'],
    'no-param-reassign': [2, { props: false }],
    'no-cond-assign': [2, 'except-parens'],
    'no-console': [2, { allow: ['warn', 'error'] }],
    'no-plusplus': [2, { allowForLoopAfterthoughts: true }],
    'no-shadow': 0,
    'no-use-before-define': 0,
    'no-useless-constructor': 0,
    'no-unused-vars': 0,
    'no-redeclare': 0,
    'import/export': 0,
    'import/no-cycle': 0,
    'import/extensions': 0,
    'import/no-unresolved': 0,
    'import/prefer-default-export': 0,
    'import/no-extraneous-dependencies': 0,
    'promise/always-return': 0,
    'promise/catch-or-return': 0,
  },
  overrides: [
    {
      files: ['**/*.js'],
      rules: {
        'no-console': 0,
        'global-require': 0,
      },
    },
  ],
}
