name: 🚀　Release
on:
  push:
    branches:
      - master
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: bubkoo/reusable-workflows/.github/actions/semantic-release-monorepo@master
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          npm-token: ${{ secrets.NPM_TOKEN }}
          test-command: test
          build-command: build
